### ISSUE TITLE
Display user details in navbar

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#102]
Display user stats, avatar/gravatar, etc. in navbar. See discussion in #54.

**Comment by stenington** [comment]
I'm changing this from code to discussion so we can figure out the approach we want to take. I think it's just a question of will we get usernames and avatars from an external service? If so which one(s)?

**Comment by stenington** [comment]
@chloeatplay I think we can use this ticket for figuring out avatars and usernames, just FYI. I think maybe the next step is on me to present some options?

**Comment by chloeatplay** [comment]
that sounds good, I was thinking of gravatar or webmaker connect that @toolness made.

**Comment by stenington** [comment]
So webmaker connect would actually allow login through a webmaker account instead of persona, whereas gravatar I think would still use persona login but then fetch user data from gravatar.

**Comment by stenington** [comment]
I guess I'm just making sure that offering alternate logins is okay.

**Comment by chloeatplay** [comment]
given persona's uncertain future, i think it only makes sense to have alternate logins. If I were to choose I would initially go with webmaker, since on the long run it might offer us a bunch of interest data. Thinking of youth, down the line offering facebook logins should probably be part of this experience.
