### ISSUE TITLE
Design UI  D10 / M10 Discovery Pathway Page, Remove parts

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#128]

**Comment by zzzndr** [comment]
Here is the screen for desktop.
Later i will upload the corresponding pages for the mobile layout.

https://redpen.io/ygprq4

**Comment by zzzndr** [comment]
ty for the feedback!
here is a new version, I thought about it before, but was doubting, because it might mean a lot of extra work for @stenington?

https://redpen.io/e6c2rt

**Comment by stenington** [comment]
@chloeatplay @zzzndr 

I have a question about the `Save` and `Cancel` controls. Some of the stuff I'm using internally makes it really easy to do stuff without having to have a separate save button, so for example you could click `Remove parts` to expose the trash can buttons, but then clicking them could just remove the item immediately instead of marking it for deletion later.

If you feel the `save` and `cancel` controls are better from a usability point of view (giving the user a chance to abort an action) then I can do it that way. If you had them because you assumed it was easier for me, I thought I should let you know it'd be just as easy to do things directly.

Let me know what you think!

**Comment by zzzndr** [comment]
@chloeatplay @stenington 

Good to know, ty!

Am i correct the storybit is only saved on a specific pathway?
And that the content of the storybit will be gone for good after it is deleted?

If so i would feel better to have a save / cancel button and as a user I would feel more comfortable with a confirmation popup asking if i _really_ want to delete my storybit (:

Good to know about the functionality (:

**Comment by stenington** [comment]
@zzzndr Ok yeah, that makes sense. Confirmation dialogs with a cancel option are probably easier to build than some sort of generic "undo".

**Comment by zzzndr** [comment]
an updated version can be found here
https://redpen.io/r4te5f

**Comment by zzzndr** [comment]
Here is the new screen for desktop
https://redpen.io/1m5yuk

confirmation popup
https://redpen.io/5a9qv4

**Comment by zzzndr** [comment]
here are new screens for desktop & mobile

D10
https://redpen.io/12euyt

D10a
https://redpen.io/4mn28o

M10
https://redpen.io/5qv3ka

**Comment by zzzndr** [comment]
Here are updated screens for desktop and mobile:

D10
https://redpen.io/12euyt

D10a
https://redpen.io/4mn28o

M10
https://redpen.io/kf8ncs

M10a
https://redpen.io/k3tygf

**Comment by zzzndr** [comment]
Here are updated screens for mobile:

M10
https://redpen.io/amhy94

M10a
https://redpen.io/c2zx68

**Comment by chloeatplay** [comment]
:thumbsup: good to close
