### ISSUE TITLE
Design placeholder splash page on discover.openbadges.org

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-discovery#13]
Need logo (branding) and copy.

**Comment by chloeatplay** [comment]
Will start with a hacked version of the badgekit page for reference.  http://badgekit.openbadges.org/

**Comment by iamjessklein** [comment]
What content needs to go on the Splash page?

**Comment by chloeatplay** [comment]
Splash Page needs to contain a) Logo for Discovery similar to Badgekit page. b) A small paragraph containing info about the project c)Subscribe for updates? d) Footer with gates & openbadges logos e) Advisory Group photos (6 people) & Partnens (3-4) ==> not sure this would go to splash page, but noting it here since it gives project some prestige. 
In terms of style, should link to openbadges logo familly- but also meant for an audience of teens, so should reflect a certain level of playfulness and such.

**Comment by threeqube** [comment]
:+1:

**Comment by iamjessklein** [comment]
cc:/ @adiladiladil

**Comment by ghost** [comment]
Here is a link to a pdf that has some typeset for Discovery

https://www.dropbox.com/s/q7xz1nzmvi5byvh/BadgeKit%20Discovery.pdf

i feel the mozilla type is throwing it off a bit. if it wasn't there either left or right justified "discovery" would look natural and not too text heavy

**Comment by chloeatplay** [comment]
Lets discuss tomorrow- there are many words going on here ;) Might be worth trying just Discovery.

**Comment by threeqube** [comment]
Also the text "discovery" feels a little too "weak" or light here if that makes any sense.

**Comment by ghost** [comment]
what weight should discovery hold?
same as mozilla or somewhere in between that and how discovery looks now?

**Comment by threeqube** [comment]
I should let @chloeatplay weigh in on that. Maybe best we discuss as @chloeatplay suggests?

**Comment by chloeatplay** [comment]
Good question @adiladiladil :octopus: There are many ways to approach this and I think it will all be clear once we sync on top-level goals for Discovery as well as logo in tomorrows call. In the meantime, a way to think of this product is as a stand-alone project within Badgekit that holds its own weight and has a particular audience of youth (15+ and precollege). It needs to somehow convey it is part of the OpenBadges familly but can have its distinct style and feel a little bit separate. I hope this helped a little bit, looking forward to hearing your ideas and talking about this moaRrrr tomorrow :dancer:

**Comment by ghost** [comment]
I'm attaching two links to some thoughts I had for the Discovery splash page

Because it's for a younger audience, I chose to use primary colors. It says education, fundamentals, building blocks and the classroom.

It's a scrolling splash page separated into three sections.
The way discovery was described to me it sounded like pathways and the nature of how one accomplishment leads to another to another. The scrolling splash page functions similarly where the first section leads to the second and so on

It'd be great to see the header fixed so as one scrolls the discovery logo and the email submit bar would always remain on top. might work, might not. 

https://redpen.io/dose3q
https://www.dropbox.com/s/q01q2dhg20nhywj/Discovery-Splash-Page-03.jpg
https://www.dropbox.com/s/t1loj72cdk4z9h6/Discovery-Splash-Page-02.jpg

**Comment by chloeatplay** [comment]
Hey @adiladiladil great work as discussed over phone. A note about timing; looks like we will need a final design EOW to get things moving with studio MoFo who might be able to do the coding for us. Does that seem doable? Another note on the advisory group part- aside from photos we will need to have name and job affiliation, i.e. Adil Adil- Dean of Impeccable Design at The University Of Design Wizardy

**Comment by ghost** [comment]
that is doable

if you could get me any copy/text that is finalized as well as photos/names/job afilliations for the advisory group I can begin plugging those details in

thanks chlo!

**Comment by chloeatplay** [comment]
Great-a) photos will have by EOW b) Copy by tomorrow EOD. Thanks @adiladiladil  :dancer:

**Comment by chloeatplay** [comment]
Hey @adiladiladil looks like we will have to cram everything together tomorrow. Photos are still on the way and copy in progress. Please use placeholder text for now and no pics. I will send those assets to the MoFo Studio team all together. Thanks again :dancer:

**Comment by ghost** [comment]
wonderful. at this point, what do you need from me? the illustrator files?

**Comment by chloeatplay** [comment]
Oui. Updated illustrator files, with the small tweaks we discussed over phone if possible. No head on top slide & pathways looking a bit more branching on second slide.
Merci !

**Comment by chloeatplay** [comment]
@adiladiladil some text here (still waiting to be reviewed) but can give you an idea. :bulb: https://openbadges.etherpad.mozilla.org/discovery-copy

**Comment by ghost** [comment]
@chloeatplay this etherpad doc won't open for me
can you resend some other way?

**Comment by chloeatplay** [comment]
@adiladiladil should work now, final text ready too!

**Comment by ghost** [comment]
@chloeatplay can you please seperate the FINAL FINAL copy for this

it's a bit all over the place and not entirely sure which version is the final

**Comment by chloeatplay** [comment]
Clean version in issue #90 Sorry for the mixup :pray:

**Comment by ghost** [comment]
here is the update

https://www.dropbox.com/s/46wx4nrm2nwffbi/Discovery%20Splash%20Page-01.jpg
not sure what you want to do about the logo

and are we still including photos of the advisory people?

**Comment by chloeatplay** [comment]
The logo as I understood would be the orange one from the collection. I am happy with that solution. As per the revised wireframes those do not include any indication of what you are looking for in the first section, or the fact that pathways are not linear in the second section. I am happy to wrap this up due to our deadline if you can send me the ai. files. Thanks!

**Comment by ghost** [comment]
here is a link to the ai file

https://www.dropbox.com/s/tzhgm2od9ilfh1g/Discovery%20Splash%20Page.ai

**Comment by ghost** [comment]
@chloeatplay https://www.dropbox.com/s/tzhgm2od9ilfh1g/Discovery%20Splash%20Page.ai

**Comment by chloeatplay** [comment]
@adiladiladil can you please provide typeface font and size, thanks!

**Comment by ghost** [comment]
@chloeatplay 
Title : opensans extrabold 40pt
body : opensans light 17pt

**Comment by chloeatplay** [comment]
Grazie, @adiladiladil  can you send me ai. file of previous iteration as well with head?

**Comment by chloeatplay** [comment]
Design & assets complete. Minor changes applied to @adiladiladil 's playful design such as replacing white head with badge, moving sign up button to first frame (so we can fit mozilla tab on top) and changed shape of badges in pathway to match our standard badge shape. Also included space for names in the advisory group part. 
![discovery splash page_cover-01](https://f.cloud.github.com/assets/1945209/2235069/a9695bd8-9b42-11e3-8919-ec4c121c4835.png)

*Note: waiting on names/photos of advisory group. We will go with placeholders for now.

**Comment by threeqube** [comment]
Looks great! :+1:

**Comment by megcolek** [comment]
This looks great!
