### ISSUE TITLE
Design UI for D6 / M6a, M6b Discovery Pathway Page, View Similar

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#133]

**Comment by zzzndr** [comment]
Here are the screens for D6, the mobile screens will follow!

D6 a
https://redpen.io/63129p
- Clicking anywhere on the badge will open the badge popup with info (D6 b)
- Clicking on the checkbox in the top right corner of a badge will select the badge immediately & will bring you to D6 c

D6a variant 2
https://redpen.io/kt572z

Like D6 a, only difference is the ‘i’ in the top left corner of a badge to make it obvious that by clicking you will get more info about the badge.

D6 b
https://redpen.io/bpy2kc

I haven’t seen this screen in the wireframe, included it because it makes sense to me (: Perhaps for a future version?

D6 c
https://redpen.io/oapum7

D6 d
https://redpen.io/4vxpjt

**Comment by zzzndr** [comment]
Here are a view possibilities for an information text overlay
https://redpen.io/tarnjx

**Comment by zzzndr** [comment]
here is an updated version (:
https://redpen.io/src7of

**Comment by zzzndr** [comment]
Here are the mobile screens:

M6a
https://redpen.io/qh14tf

M6b
https://redpen.io/b37u89

**Comment by zzzndr** [comment]
updated mobile screen M6a
https://redpen.io/352fqk

**Comment by chloeatplay** [comment]
THis looks good to me, lets close the issue if you are ok with that sander ? :thumbsup:

**Comment by zzzndr** [comment]
sounds like music to my ears ((:

**Comment by chloeatplay** [comment]
:musical_note: :musical_keyboard: :musical_score:
