### ISSUE TITLE
Swappable badge/pathway source

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#144]
In the current planned architecture, the discovery app uses the directory as a source of badge classes, and itself as a source of pathways (either defined manually by us or built by a user using the tool). The idea was floated around at DML that maybe the discovery app could also interchangeably use an instance of badgekit as its source of badges and presumably pathways as well (that would be defined through an interface in some future version of badgekit). 

This seems possible, although it requires some thinking. For one thing, it means anything built into the directory would have to be replicated in badgekit (i.e. recommendations) or moved over to the discovery app's DB to be portable across back-ends. This might mean that the discovery backed has to be a lot smarter about badge classes, but I'm not entirely sure.

**Comment by threeqube** [comment]
cc/ @cmcavoy

**Comment by stenington** [comment]
I think there's also a question of how front-end pieces get integrated into other sites, or whether they do at all. I wonder if the notion is to expose the same API that the discovery app uses to a badgekit user so they can build their _own_ front-end on top of the badges and pathways, or more to provide ready-made widgets they can put on the site they have to build.

Also as a note, I don't think we're ready to take that on yet. I think we're still in the early stages of exploring what pathway tools should look like, and making widgets out of it makes more sense when we understand that space better.

**Comment by jpcamara** [comment]
It's an interesting concept - definitely needs a lot more definition though.
- What will the api look like?
  - Will badgekit and directory both conform to an api that is consistent and standard?
- Will pathways have to create two swappable modules for api integration depending on if it's badgekit or directory?
- Would adding pathways to badgekit dilute the purpose of badgekit or enhance it?
- If the directory is already indexing badges then theoretically it has all the badges already and what would badgekit exposing them additionally offer? Is there an expanded featureset that would be considered here since badgekit is more than just a badge class listing?

I agree that taking this on now is probably premature, since pathways themselves are such a new concept.
