### ISSUE TITLE
Backend API and data loading strategy

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#180]
I think we should draft a general description of the endpoints and data loading strategies that would support the front-end as we understand it. The endpoints I expect will map closely to front-end models, although I'd like someone with experience to weigh in on the best way to handle nested models, and I know we have at least one slightly special case of "cloning" a pathway. By data loading strategies, I mean figuring out when to load different data sets asynchronously, when we can/should bootstrap data, etc. Having a plan around this should make collaboration easier.

**Comment by stenington** [comment]
Here's a straw-man proposal:

## Types
- **Achievement**: holds the common data between badges and pathways like title, description, tags
  - **Badge**: has additional data like issuer, criteria
  - **Pathway**: has additional sub-components like Requirements, Notes, and Milestones*
- **Requirement**: connects a Pathway to a Badge with a physical x,y positioning
- **Note**: a human-entered note on a Pathway
- **User**: a human being's account in the system

\* = in future version

## Endpoints
- **/directory** - lists Achievements
  - **/:id** - a single Achievement
- **/badge** - lists Badges
  - **/:id** - a single Badge
- **/pathway** - lists Pathways
  - **/:id** - a single Pathway
    - **/requirement** - lists a Pathway's Requirements
      - **/:id** - a single Requirement
    - **/note** - lists a Pathway's Notes
      - **/:id** - a single Note
- **/user** - lists Users
  - **/:id** - a single User
    - **/favorite** - a list of Achievements a User has favorited
    - **/earned** - a list of Badges a User has earned and shared through their Backpack
    - **/pledged** - a list of Pathways a User has pledged to do

**Comment by chloeatplay** [comment]
this looks good to me :thumbsup: 
small nit-picky thing ==> would change /wishlist  to /favorites for consistency (we re changing that in the copy too)

**Comment by stenington** [comment]
Assuming the above is somewhat reasonable, some questions I then have:
- Is it wasteful in some way to have e.g. the pathway editor have to hit several endpoints to fetch all the data it needs? (/pathway/:id, /pathway/:id/requirement, /pathway/:id/note) Or conversely is it wasteful if /pathway/:id includes a full representation including requirements and notes?
- As a general Backbone strategy, is it preferable to build views off data you already have on the frontend, or does it work out better to let pages request the data they need? Particularly when going from a page that can treat a Pathway as an Achievement, for example, should the Pathway detail page just pull the extra data when someone goes there, or does it make more sense to send it all over on the listing page and then operate off of frontend data?
- Is it helpful to provide endpoints like /requirement and /requirement/:id off the root as well, or does Backbone make url-building easy for sub-collections?
- Does a /directory endpoint make sense, or is it better to hit /badge and /pathway and mix the results on the frontend?
- How do we handle special actions like "pledge" on a pathway, where the result should be an identical Pathway with identical Requirements but different User ownership. Should we provide a special endpoint for that, or POST with all the data to /user/:id/pledged, or something like that?

Some of these questions may be premature optimization and it's okay to just pick a way and try it out, but I don't have a gut feel for it yet and Backbone can kind of lead you down some dead ends in my experience.

**Comment by stenington** [comment]
@jpcamara If you have a chance to weigh in here, I'd appreciate it.

**Comment by stenington** [comment]
I guess the other detail is what actions would be allowed on which endpoints. Some of them are GET only, and I think all that support PUT or POST will do so for certain users only. Is there a particularly good way to handle that with Backbone?

**Comment by divideby0** [comment]
We've typically used some sort of session identifier to authenticate user requests.  This is a common compromise to pure REST as otherwise we're doing HTTP basic authentication on every request.  The workflow would work as follows:
1. User logs in and we store their persona metadata.
2. Node server authenticates and stores a random session token in a distributed key/value store like Redis, returning the identifier back to the user in the form cookie. Alternatively, we can store the authenticated username directly in a node session so long as it's backed by a distributed store: http://blog.modulus.io/nodejs-and-express-sessions#using-redis
3. Backbone augments its Persona-driven `User` backbone model with the session token.
4. We decorate the `Backbone.Model.sync` method to include the session identifier in any future request headers. (We wouldn't need to do this explicitly if we use Node.js sessions).
5. When the node server receives a secured request, it compares the session token against the one stored in the key/value store to validate if the user is logged on.

To avoid session hijacking, we'd also likely want to do this all via HTTPS. There are more sophisticated approaches with fancy key rotation schemes on each request but that's probably overkill.

Another question, do we ever expect that we'd need to expose this API to third-parties? If so, should we consider OAuth 2.0 at some point.

**Comment by divideby0** [comment]
Also, to address some of the earlier points...

> Is it wasteful in some way to have e.g. the pathway editor have to hit several endpoints to fetch all the data it needs?

Yes, probably.  However, we've had a lot of success starting from the perspective of clean resource-oriented design and then building "page resources" that are better optimized for the multiple resources/properties into a single request.  Lazily loading properties through a mechanism like `$ref` in [JSON Schema](http://json-schema.org/example2.html) can help bridge the gap, but I don't believe this is supported out the box in Backbone or Human.

> As a general Backbone strategy, is it preferable to build views off data you already have on the frontend, or does it work out better to let pages request the data they need?

If I understand the question correctly, I think ultimately you have to support both retrieval cases as the user can land in at any endpoint (assuming you're using routes, etc). The simplest approach is to create several single-page apps instead of one big multi-page app.  In this case, each single-page app would be responsible for pulling in its own data, but we could still share models, etc.  We can also utilize caching/etags to reduce HTTP traffic in this mode potentially. But if we want one pure single-page app, we'll likely need to deal a fair bit with sync logic from page to page.

> Is it helpful to provide endpoints like /requirement and /requirement/:id off the root as well, or does Backbone make url-building easy for sub-collections?

Pure Backbone allows for models to contain attributes that are collections, but you typically have to deal with the `fetch` and `set` logic manually.  I'm not sure if HumanJS makes this easier.

> How do we handle special actions like "pledge" on a pathway, where the result should be an identical Pathway with identical Requirements but different User ownership.

This one is a bit tricky, but the way I've approached it before is something like:

```
POST /user/:id/pledges

{"pathway.id": 5}
```

This creates a new pledge/pathway id which can be accessed from either `/user/:id/pledges/:newPathwayId` or `/pathway/:newPathwayId`.

**Comment by stenington** [comment]
Awesome! This was super helpful. Closing out this big ticket, can open more specific ones if needed.
