### ISSUE TITLE
Badge in pathway editor should take you to badge page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#287]
As per yesterdays stand, when you click on a badge in the pathway editor that should take you to the badge page

**Comment by chloeatplay** [comment]
There is a little :bug: right now when you try to delete, and click the x" the "click" takes you to the badge page. We can try to fix that and if its still confusing try per @zzzndr's suggestion to just make the badge title clickable.

**Comment by zzzndr** [comment]
for reference:
https://github.com/mozilla/openbadges-discovery/pull/308

**Comment by stenington** [comment]
What do you think about linking to the badge page on double-clicks?

**Comment by chloeatplay** [comment]
ah! would have to try it out- but i think that would work well actually!

**Comment by stenington** [comment]
I guess having the title text look like a link gives a clearer hint to the user that it's clickable and doing so will take them to a new page. But, linking on double click is a smaller code change so I'll try that first and see what everyone thinks.

**Comment by stenington** [comment]
Wow I'm not even sure canvas supports underlining fonts. It seems to support anything you can specify in a CSS font property, but underline is specified as a text-decoration so I don't think it's supported! :-1:

So the way to go to get the titles to be links I think would be to attempt this DOMElement thing again. I suspect the elements are getting misaligned because of CSS resizing of the canvas which seems to confuse the hell out of everything. 

But before I delve into that I'm just going to hope double-click works for now.

**Comment by stenington** [comment]
Double-click seems to have the thumbs up
