### ISSUE TITLE
Discuss mobile first design implications on development

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-discovery#3]
@chloeatplay has done a good amount of research and is considering mobile first design for discovery/pathways/directory. 

Need to figure out development implications of mobile first design. 

cc/ @stenington @kayaelle

**Comment by stenington** [comment]
Another way to think about this is "who's the key user, and what browser and device are they using" and then we can discuss the implications of targeting that.

**Comment by stenington** [comment]
Oops, submitted too soon.

I don't particularly have a problem targeting mobile browsers if that's where the users are, but it'll have some implications for the scope of the project of course. Alternatively if they're most likely going to be using IE8 on public library computers, it would be good to design for that up front as well.

I think generally speaking, the more specific and focused we can be about where the app has to work, the more time we have to build in functionality because testing can be quicker and compatibility concerns are less pressing. The more we want it to work everywhere, the longer it takes to test and QA, the more conservative we have to be in what technologies we use, and we'll end up having less time to build in features.

**Comment by cmcavoy** [comment]
:+1:

**Comment by iamjessklein** [comment]
As a reference, there are some great books on this. I particularly recommend this one: http://www.abookapart.com/products/mobile-first by Luke Wroblewski. 

From the design perspective - which I think can also be applied to the development perspective - what's particularly nice about this approach is that you are able to reduce the interactions and content to what is essential. This allows for a no nonsense approach to the design. 

I agree with what you wrote @stenington

**Comment by kayaelle** [comment]
That's an excellent book @iamjessklein !
