### ISSUE TITLE
Clicking on badges

### ISSUE THREAD

**Issue by jadeforester** [mozilla/openbadges-discovery#410]
Hey guys,

Is there any way to make the pathway badges single-click instead of double?

I vaguely remember seeing this feedback a few weeks back, and have had a couple of folks asking about it on Twitter.

-Jade

**Comment by stenington** [comment]
It's certainly technically possible, and I think the overall feedback we're getting is that double-click isn't ideal. 

The rationale behind double-click was that the distinction between a single click and a drag can be a bit blurred (if the mouse moves slightly while you're clicking, for example) and instead of treading that fine line we thought double-click might work out instead. 

As for _when_ that change might be made, we're in code freeze until we demo at the very least, so for now things will stay as they are.
